insert into Ingredient (id, name, type) values ('FLTO', 'FlourTortilla', 'WRAP');
insert into Ingredient (id, name, type) values ('COTO', 'CornTortilla', 'WRAP');
insert into Ingredient (id, name, type) values ('GRBF', 'GroundBeef', 'PROTEIN');
insert into Ingredient (id, name, type) values ('CARN','Carnitas', 'PROTEIN');
insert into Ingredient (id, name, type) values ('TMTO', 'DicedTomatoes', 'VEGGIES');
insert into Ingredient (id, name, type) values ('LETC','Lettuce', 'VEGGIES');
insert into Ingredient (id, name, type) values ('CHED','Cheddar', 'CHEESE');
insert into Ingredient (id, name, type) values ('JACK','Monterrey Jack', 'CHEESE');
insert into Ingredient (id, name, type) values ('SLSA', 'Salsa','SAUCE');
insert into Ingredient (id, name, type) values ('SRCR', 'SourCream', 'SAUCE');
insert into User (id, city, fullname, password, phone_number, state, street, username, zip) values(1, 'test', 'test', 'eb490f34ecc1ec21c1a0be2007a684a2966a7b1999b4d14b025f47cbb07954d2ec4c69160a15aee9', 88888888888, 'test', 'test', 'test', 'test');
